name: General care information
order: 4

steps:
  - name: Caring for this young person
    slug: caring-for-young-person
    questions:
      - current-behaviour
      - negative-impact-on-behaviour
      - positive-impact-on-behaviour
      - religious-or-cultural-needs
      - first-language
      - additional-care-information
